# https://gitlab.com/cmdjulian/mopy/-/ci/lint

include:
  # Gitlab Templates for Static Security and Secretes detection
  - template: Security/Secret-Detection.gitlab-ci.yml
  # Gitlab static scanning
  - template: Security/SAST.gitlab-ci.yml
  # dependabot
  - local: /.gitlab/.dependabot.gitlab-ci.yml
  # container build
  - project: cmdjulian/git-lab-ci-container-building-templates
    file: buildkit.gitlab-ci.yml


stages: [ test, docker ]


secret_detection:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

sast:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never

container-image:
  stage: docker
  extends: .buildkit
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"
      changes: [ 'Dockerfile', 'go.mod', '*.go', '.gitlab-ci.yml' ]
  variables:
    PUSH_IMAGES: $CI_REGISTRY_IMAGE:v1,$CI_REGISTRY_IMAGE:latest,cmdjulian/mopy:v1,cmdjulian/mopy:latest
    TARGETPLATFORM: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
  tags: [ docker ]