include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - docker

sast:
  stage: test

docker:
  stage: docker
  image:
    name: moby/buildkit:latest
    entrypoint: [ "sh", "-c" ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs: [ ]
  dependencies: [ ]
  services:
    - alias: buildkitd
      name: moby/buildkit:rootless
      command: [ --oci-worker-no-process-sandbox, --addr, tcp://0.0.0.0:1234 ]
  variables:
    BUILDKIT_HOST: tcp://buildkitd:1234
    IMAGE_TAG_RELEASE: $CI_REGISTRY_IMAGE:v1
    IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  before_script:
    - mkdir ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}"
      > ~/.docker/config.json
  script: >-
    buildctl build
    --frontend=dockerfile.v0
    --local context=.
    --local dockerfile=.
    --import-cache type=registry,ref=$IMAGE_TAG_LATEST
    --export-cache type=inline
    --output type=image,\"name=$IMAGE_TAG_RELEASE,$IMAGE_TAG_LATEST\",push=true

.docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.8.1-debug@sha256:3bc3f3a05f803cac29164ce12617a7be64931748c944f6c419565f500b65e8db
    entrypoint: [ "" ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs: [ ]
  dependencies: [ ]
  variables:
    IMAGE_TAG_RELEASE: $CI_REGISTRY_IMAGE:v1
    IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}"
      > /kaniko/.docker/config.json
  script: >-
    /kaniko/executor
    --use-new-run
    --context="$CI_PROJECT_DIR"
    --dockerfile="$CI_PROJECT_DIR/Dockerfile"
    --destination="$IMAGE_TAG_RELEASE"
    --destination="$IMAGE_TAG_LATEST"
    --single-snapshot
    --reproducible
    --log-format=color
    --log-timestamp=true
